--This file is automatically generated by generate_VHDL_file.m, 09-Sep-2020

library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

package CONFIG is
    constant weight_size  	: integer := 8;  	--Weight size
	constant data_size 		: integer := 16;	--Data size

	constant output_classes : integer := 10;	--Number os possible outputs
end CONFIG;